# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  proto:
    desc: generate new protobuf files
    cmds:
      - protoc --proto_path=./api/proto --go_out=./api/proto --go_opt=paths=source_relative --go-grpc_out=./api/proto  --go-grpc_opt=paths=source_relative ./api/proto/client.proto --grpc-gateway_out ./api/proto --grpc-gateway_opt paths=source_relative
    silent: true