# https://taskfile.dev

version: '3'

tasks:
  proto:
    desc: generate new protobuf files
    cmds:
      - protoc --proto_path=./api/grpc/proto --go_out=./api/grpc/proto --go_opt=paths=source_relative --go-grpc_out=./api/grpc/proto  --go-grpc_opt=paths=source_relative ./api/grpc/proto/client.proto --grpc-gateway_out ./api/grpc/proto --grpc-gateway_opt paths=source_relative
    silent: true