// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: client.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientClient interface {
	InsertHospital(ctx context.Context, in *InsertHospitalRequest, opts ...grpc.CallOption) (*InsertHospitalReply, error)
	QueryNearestHospitals(ctx context.Context, in *QueryNearestHospitalsRequest, opts ...grpc.CallOption) (*QueryNearestHospitalsReply, error)
}

type clientClient struct {
	cc grpc.ClientConnInterface
}

func NewClientClient(cc grpc.ClientConnInterface) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) InsertHospital(ctx context.Context, in *InsertHospitalRequest, opts ...grpc.CallOption) (*InsertHospitalReply, error) {
	out := new(InsertHospitalReply)
	err := c.cc.Invoke(ctx, "/Client/InsertHospital", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) QueryNearestHospitals(ctx context.Context, in *QueryNearestHospitalsRequest, opts ...grpc.CallOption) (*QueryNearestHospitalsReply, error) {
	out := new(QueryNearestHospitalsReply)
	err := c.cc.Invoke(ctx, "/Client/QueryNearestHospitals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServer is the server API for Client service.
// All implementations must embed UnimplementedClientServer
// for forward compatibility
type ClientServer interface {
	InsertHospital(context.Context, *InsertHospitalRequest) (*InsertHospitalReply, error)
	QueryNearestHospitals(context.Context, *QueryNearestHospitalsRequest) (*QueryNearestHospitalsReply, error)
	mustEmbedUnimplementedClientServer()
}

// UnimplementedClientServer must be embedded to have forward compatible implementations.
type UnimplementedClientServer struct {
}

func (UnimplementedClientServer) InsertHospital(context.Context, *InsertHospitalRequest) (*InsertHospitalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertHospital not implemented")
}
func (UnimplementedClientServer) QueryNearestHospitals(context.Context, *QueryNearestHospitalsRequest) (*QueryNearestHospitalsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryNearestHospitals not implemented")
}
func (UnimplementedClientServer) mustEmbedUnimplementedClientServer() {}

// UnsafeClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServer will
// result in compilation errors.
type UnsafeClientServer interface {
	mustEmbedUnimplementedClientServer()
}

func RegisterClientServer(s grpc.ServiceRegistrar, srv ClientServer) {
	s.RegisterService(&Client_ServiceDesc, srv)
}

func _Client_InsertHospital_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertHospitalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).InsertHospital(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/InsertHospital",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).InsertHospital(ctx, req.(*InsertHospitalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_QueryNearestHospitals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNearestHospitalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).QueryNearestHospitals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Client/QueryNearestHospitals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).QueryNearestHospitals(ctx, req.(*QueryNearestHospitalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Client_ServiceDesc is the grpc.ServiceDesc for Client service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Client_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertHospital",
			Handler:    _Client_InsertHospital_Handler,
		},
		{
			MethodName: "QueryNearestHospitals",
			Handler:    _Client_QueryNearestHospitals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
